FROM jenkins/ssh-agent:jdk11

# This is ARG because is used only during the build
# Difference with ENV? ENV is available to the container when it is running
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt install curl unzip -y && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install

RUN apt update && apt-get install -qy gnupg wget lsb-release make

RUN wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list && \
    apt update && apt-get install terraform

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
